version: "2.4"
services:
    confluence:
        image: repository.dotin.ir/atlassian/confluence:latest
        #stdin_open: true # docker run -i
        #tty: true        # docker run -t
        # environment:
        ports: 
            - "8090:8090"
            - "8091:8091"
        restart: always
        container_name: confluence
        volumes: 
            - ~/confluenceVolume:/var/atlassian/application-data/confluence
volumes:
    confluenceVolume:




