version: "2.4"

services:
    jenkins:
        image: docker/jenkins/jenkins:lts
        privileged: true
        user: root
        ports:
          - 8080:8080
          - 50000:50000
        container_name: myjenkins
        hostname: jenkins
        volumes:
          - ~/jenkins_data:/var/jenkins_home
          - /var/run/docker.sock:/var/run/docker.sock




