version: "2.4"
services:
    postgresql_database:
        image: repository.dotin.ir/postgres:latest
        #stdin_open: true # docker run -i
        #tty: true        # docker run -t
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin1234
            - POSTGRES_DB=productDb
        ports: 
            - "5432:5432"
        restart: always
        volumes: 
            - ~/database-data:/var/lib/postgresql/data/

    pgadmin:
        image: repository.dotin.ir/dpage/pgadmin4
        environment: 
            - PGADMIN_DEFAULT_EMAIL=so.novin@dotin.ir
            - PGADMIN_DEFAULT_PASSWORD=admin1234
        ports:
            - '5050:80'
        restart: always
        volumes: 
            - pgadmin:/root/.pgadmin
volumes:
    database-data:
    pgadmin:




