---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: devops-jenkins-pv
  namespace: devops
  labels:
    type: glusterfs
    app: jenkins-deployment
spec:
  storageClassName: managed-gluster
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: glusterfs-cluster
    path: k8s-volume/jenkins
    readOnly: false
