---
apiVersion: v1
kind: Namespace
metadata:
  name: middleware
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitbucket
  namespace: middleware
  labels:
    app: bitbucket
spec:
  selector:
    matchLabels:
      app: bitbucket
  replicas: 1
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: bitbucket
      labels:
        app: bitbucket
    spec:
      containers:
      - name: bitbucket
        image: repository.dotin.ir/atlassian/bitbucket:latest
        ports:
        - name: readiness-port
          containerPort: 7990
          hostPort: 7990
        - name: port2
          containerPort: 7999
          hostPort: 7999
        readinessProbe:
          periodSeconds: 60
          initialDelaySeconds: 60
          httpGet:
            path: /
            port: readiness-port
            scheme: HTTP
        livenessProbe:
          periodSeconds: 60
          initialDelaySeconds: 60
          httpGet:
            path: /
            port: readiness-port
            scheme: HTTP
        imagePullPolicy: Always
        # resources:
        #     requests:
        #       memory: "5.5Gi"
        #       cpu: "6000m"
        #     limits:
        #       memory: "5.5Gi"
        #       cpu: "6000m"
        #       ephemeral-storage: "500Mi"
        volumeMounts:
            - mountPath: /var/atlassian/application-data/bitbucket
              name: middleware-bitbucket-pv
        securityContext:
          runAsGroup: 0
          runAsUser: 0

          
      volumes:
        - name: middleware-bitbucket-pv
          persistentVolumeClaim:
            claimName: middleware-bitbucket-pvc

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: middleware-bitbucket-pv
  namespace: middleware
  labels:
    type: glusterfs
    app: bitbucket
spec:
  storageClassName: managed-gluster
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: glusterfs-cluster
    path: k8s-volume/bitbucket
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: middleware-bitbucket-pvc
  namespace: middleware
  labels:
    app: bitbucket
spec:
  storageClassName: managed-gluster
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: "middleware-bitbucket-pv"

---
apiVersion: v1
kind: Service
metadata:
  name: bitbucket-svc
  labels:
    app: bitbucket
  namespace: middleware
spec:
  selector:
    app: bitbucket
  type: NodePort
  ports:
  - protocol: TCP
    port: 7990
    #nodePort: 30555
  # sessionAffinity: ClientIP
  # sessionAffinityConfig:
  #   clientIP:
  #     timeoutSeconds: 300
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: bitbucket
  name: bitbucket
  namespace: middleware
  # annotations:
  #   nginx.org/ssl-services: "bitbucket-svc"
  #   nginx.ingress.kubernetes.io/affinity: cookie
  #   nginx.ingress.kubernetes.io/session-cookie-name: "JSESSIONID"
  #   nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  #   nginx.ingress.kubernetes.io/affinity-mode: persistent
  #   nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
  #   nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
  #   nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
spec:
  ingressClassName: nginx
  # tls:
  # - hosts:
  #     - fcbcms.bank.dotin.ir
  #   secretName: tls-secret
  rules:
  - host: bitbucket.bank.dotin.ir
    http:
      paths:
      - backend:
          service:
            name: bitbucket-svc
            port:
              number: 7990
        path: /
        pathType: Prefix