---
apiVersion: v1
kind: Namespace
metadata:
  name: middleware
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: confluence
  namespace: middleware
  labels:
    app: confluence
spec:
  selector:
    matchLabels:
      app: confluence
  replicas: 1
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: confluence
      labels:
        app: confluence
    spec:
      containers:
      - name: confluence
        image: repository.dotin.ir/atlassian/confluence:latest
        ports:
        - name: readiness-port
          containerPort: 8090
          hostPort: 8090
        - name: port2
          containerPort: 8091
          hostPort: 8091
        
        # readinessProbe:
        #   periodSeconds: 60
        #   initialDelaySeconds: 60
        #   httpGet:
        #     path: /
        #     port: readiness-port
        #     scheme: HTTP
        # livenessProbe:
        #   periodSeconds: 60
        #   initialDelaySeconds: 60
        #   httpGet:
        #     path: /
        #     port: readiness-port
        #     scheme: HTTP
        imagePullPolicy: Always
        # resources:
        #     requests:
        #       memory: "5.5Gi"
        #       cpu: "6000m"
        #     limits:
        #       memory: "5.5Gi"
        #       cpu: "6000m"
        #       ephemeral-storage: "500Mi"
        volumeMounts:
            - mountPath: /var/atlassian/application-data/confluence
              name: middleware-confluence-pv
        securityContext:
          runAsGroup: 0
          runAsUser: 0

          
      volumes:
        - name: middleware-confluence-pv
          persistentVolumeClaim:
            claimName: middleware-confluence-pvc

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: middleware-confluence-pv
  namespace: middleware
  labels:
    type: glusterfs
    app: confluence
spec:
  storageClassName: managed-gluster
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: glusterfs-cluster
    path: k8s-volume/confluence
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: middleware-confluence-pvc
  namespace: middleware
  labels:
    app: confluence
spec:
  storageClassName: managed-gluster
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: "middleware-confluence-pv"

---
apiVersion: v1
kind: Service
metadata:
  name: confluence-svc
  labels:
    app: confluence
  namespace: middleware
spec:
  selector:
    app: confluence
  type: NodePort
  ports:
  - protocol: TCP
    port: 8090
    #nodePort: 30555
  # sessionAffinity: ClientIP
  # sessionAffinityConfig:
  #   clientIP:
  #     timeoutSeconds: 300
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: confluence
  name: confluence
  namespace: middleware
  # annotations:
  #   nginx.org/ssl-services: "confluence-svc"
  #   nginx.ingress.kubernetes.io/affinity: cookie
  #   nginx.ingress.kubernetes.io/session-cookie-name: "JSESSIONID"
  #   nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  #   nginx.ingress.kubernetes.io/affinity-mode: persistent
  #   nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
  #   nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
  #   nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
spec:
  ingressClassName: nginx
  # tls:
  # - hosts:
  #     - fcbcms.bank.dotin.ir
  #   secretName: tls-secret
  rules:
  - host: confluence.bank.dotin.ir
    http:
      paths:
      - backend:
          service:
            name: confluence-svc
            port:
              number: 8090
        path: /
        pathType: Prefix