---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-grafana-pvc
  namespace: monitoring
  labels:
    app: grafana-deployment
spec:
  storageClassName: managed-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: "monitoring-grafana-pv"
