---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-grafana-pv
  namespace: monitoring
  labels:
    type: glusterfs
    app: grafana-deployment
spec:
  storageClassName: managed-gluster
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: glusterfs-cluster
    path: k8s-volume/grafana
    readOnly: false
