---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-grafana-pv
  namespace: monitoring
  labels:
    type: nfs
    app: grafana-deployment
spec:
  storageClassName: managed-nfs
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.100.8.146
    path: "/appserver/nfs_share/ali_pvs/grafana"
