---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster-sts
  namespace: redis-cluster
spec:
  serviceName: redis-cluster
  replicas: 6
  selector:
    matchLabels:
      app: redis-cluster-sts
  template:
    metadata:
      labels:
        app: redis-cluster-sts
    spec:
      containers:
      - name: redis
        image: docker.io/redis:5.0.1-alpine
        ports:
        - containerPort: 6379
          name: client
        - containerPort: 16379
          name: gossip
        command: ["/conf/update-node.sh", "redis-server", "/conf/redis.conf"]
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: conf
          mountPath: /conf
          readOnly: false
        - name: redis-cluster-pvc
          mountPath: /data
          readOnly: false
      volumes:
      - name: conf
        configMap:
          name: redis-cluster-cm
          defaultMode: 0755

  volumeClaimTemplates:
  - metadata:
      name: redis-cluster-pvc
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: longhorn
      resources:
        requests:
          storage: 50Mi