---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-server-pv
  namespace: monitoring
  labels:
    type: glusterfs
    app: server-deployment
spec:
  storageClassName: managed-gluster
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: glusterfs-cluster
    path: k8s-volume/prometheus
    readOnly: false

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-pushgateway-pv
  namespace: monitoring
  labels:
    type: glusterfs
    app: pushgateway-deployment
spec:
  storageClassName: managed-gluster
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: glusterfs-cluster
    path: k8s-volume/pushgateway
    readOnly: false
  
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name:  monitoring-alertmanager-pv
  namespace: monitoring
  labels:
    type: glusterfs
    app: alertmanager-deployment
spec:
  storageClassName: managed-gluster
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: glusterfs-cluster
    path: k8s-volume/alertmanager
    readOnly: false
