---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-server-pv
  namespace: monitoring
  labels:
    type: nfs
    app: server-deployment
spec:
  storageClassName: managed-nfs
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.100.8.146
    path: "/appserver/nfs_share/ali_pvs/prometheus"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-pushgateway-pv
  namespace: monitoring
  labels:
    type: nfs
    app: pushgateway-deployment
spec:
  storageClassName: managed-nfs
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.100.8.146
    path: "/appserver/nfs_share/ali_pvs/pushgateway"
  
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name:  monitoring-alertmanager-pv
  namespace: monitoring
  labels:
    type: nfs
    app: alertmanager-deployment
spec:
  storageClassName: managed-nfs
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.100.8.146
    path: "/appserver/nfs_share/ali_pvs/alertmanager"